### PR TITLE
Create Unit Test for fit.py

### LINKED ISSUE #4: Create unit tests for fit.py
- errors on incorrect inputs
- rms error
- output types

### PR DESCRIPTION
**Pull request by nanjekyejoannah**
Fixes #4

This PR adds unit tests for fit.py.

### CODE REVIEW

**Comment by bqpd** [comment]
add to whitelist

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
this looks great, thanks @jnanjekye ! (and sorry for the late response). These tests should be added to [`run_tests.py`](https://github.com/convexengineering/gpfit/blob/master/gpfit/tests/run_tests.py) so that they are run along with the other tests

**Comment by jnanjekye** [comment]
@bqpd I have made necessary changes, take a look.

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
test this please

**Comment by jnanjekye** [comment]
@bqpd I will revert with changes to address the test outcomes.

**Comment by bqpd** [comment]
Awesome, thanks!

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by bqpd** [comment]
@acdljenkins could you check on Marshall? I think he's stuck in a for loop

**Comment by bqpd** [comment]
(@galbramc, anything I can help with?)

On Jan 25, 2018 20:58, "Edward Burnell" <eburn@mit.edu> wrote:

@acdljenkins could you check on Marshall? I think he's stuck in a for loop

**Comment by galbramc** [comment]
gpfit_PullRequest_PyLint is running, and I don't know why. I can't see anything wrong in the settings, and gpfit_PullRequest_Unit is working just fine...

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by pgkirsch** [comment]
@nanjekyejoannah thank you for creating this PR and I'm so sorry it sat unmerged for so long. I made some minor tweaks and have now merged it. Thanks again for the contribution!

**Pull request merged**
