### PR TITLE
Python3 compatibility. 

### PR DESCRIPTION
**Pull request by 1ozturkbe**
Had a few minutes, figured it could use a futurize.

### CODE REVIEW

**Comment by bqpd** [comment]
whitelist

**Comment by bqpd** [comment]
thanks Berk!

**Comment by whoburg** [comment]
test this please

**Comment by 1ozturkbe** [comment]
@priyappillai please don't forget to commit merges so that tests can run :)

**Comment by priyappillai** [comment]
sorry! although, is this obsolete from #86 ?

**Comment by 1ozturkbe** [comment]
hmmm why did this PR exist then? Let me check master compatibility and then close this.

**Comment by 1ozturkbe** [comment]
Master is good. I'm going to check PR testing on this repo in a few mins and close this.

**Comment by pgkirsch** [comment]
@1ozturkbe did you mean to reopen this or can it be closed again?

**Comment by 1ozturkbe** [comment]
I have no idea why this was reopened... feel free to close if it works for Py3, which I believe it does now! (Haven't been using this lately.)

**Comment by pgkirsch** [comment]
Thanks, done!

**Pull request closed without merging**
